// <auto-generated />
namespace CountryService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20160115 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160115));
        
        string IMigrationMetadata.Id
        {
            get { return "201601150247598_2016-01-15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
