// <auto-generated />
namespace TripsBlogProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2015061601 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2015061601));
        
        string IMigrationMetadata.Id
        {
            get { return "201506160839186_2015-06-16-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
