// <auto-generated />
namespace TripsBlogProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2015062001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2015062001));
        
        string IMigrationMetadata.Id
        {
            get { return "201506200316472_2015-06-20-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
